Feature: default config values (#84)
feat: add default values for main config keys

* Add Dip::Config::ConfigKeyMissingError

This commit adds the error class ConfigKeyMissingError which is used to indicate a config key is missing.

If a developer tries to access a config key that has a `nil` value, the ConfigKeyMissingError is raised with a description of which config is missing and the path to the config file.

Currently, when a config key is `nil` an error message such as "NoMethodError: undefined method `each_' for nil:NilClass" is raised.
This is an unhelpful message because the actual problem is implicit and it requires some cognitive load decipher.

By raising ConfigKeyMissingError when a config key is `nil`, developers are given explicit information about the error.

* Add default values for required config keys

By adding default values for the required config keys we can ensure we
don't get any raised errors when accessing using config key values.

The Dip::Config::ConfigKeyMissingError still comes in useful for when
new config keys are added but no default value is defined.

* Add tests for default config key values

* Update formatting to appease rubocop

Co-authored-by: Misha Merkushin <merkushin.m.s@gmail.com>